name: Config Bot

on:
  schedule:
    - cron: '0 */3 * * *'  # پشتیبان
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Main Script
        run: python main.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL: ${{ secrets.TELEGRAM_CHANNEL }}
          TELEGRAM_ADMIN_ID: ${{ secrets.TELEGRAM_ADMIN_ID }}
          AD_BUTTON_TEXT: ${{ secrets.AD_BUTTON_TEXT }}
          AD_BUTTON_URL: ${{ secrets.AD_BUTTON_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}

      # 😴 استراحت ۳۰ دقیقه‌ای در گیت‌هاب قبل از چرخه بعدی
      - name: Wait 30 Minutes
        run: sleep 1800

      # 🚀 فراخوانی چرخه بعدی
      - name: Trigger Next Cycle
        if: always()
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/main.yml/dispatches \
            -d '{"ref":"main"}'
